on:
  workflow_dispatch:
  schedule:
    - cron: 30 17 * * TUE
name: Weekly Q and A
jobs:
  weekly-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Weekly q and a
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.QANDA_ID }}
          webhook_token: ${{ secrets.QANDA_TOKEN }}
          username: "Elitepvpers"
          avatar_url: "https://i.epvpimg.com/rXjMd.png"
          message: @here weekly Q&A starting soon. If you have any questions, suggestions or other concerns we can discuss them now. Reminder: You can always come to us with any other issues at any time.
